Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/http/server.py", line 1313, 127.0.0.1 - - [30/May/2025 18:01:01] "GET /index.html HTTP/1.1" 200 -
127.0.0.1 - - [30/May/2025 18:01:06] "GET /index.html HTTP/1.1" 200 -
d:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.11/http/server.py", line 1307, in server_bind
    return super().server_bind()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/lib/python3.11/socketserver.py", line 472, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
